### PR TITLE
Added sigma_g to BKG table

### PR DESCRIPTION
**Pull request by fjaviersanchez**
@andreufont requested that we add sigma_g to the table so we can recover the original delta field.

### CODE REVIEW

**Comment by andreufont** [comment]
@fjaviersanchez - Thanks for looking at this.

I noticed that you are writing sigma_g as an array of length Nr, but I believe it should just be a number, isn't it? It is a property of the initial Gaussian field, generated in a grid, without redshift evolution.

**Comment by fjaviersanchez** [comment]
Yes, that's correct. I did that because this was the easiest thing to do but, if you want, I can change it and add it to a header.

**Comment by andreufont** [comment]
If it is not difficult, I'd rather have a single number. Otherwise others might think that it is a function of redshift, and not a constant.

**Comment by fjaviersanchez** [comment]
@andreufont I took out sigma_g from the table and put it on the header of the skewers density hdu (3rd extension, hdu[2]). Please, check it out and let me know if this is better.

**Comment by andreufont** [comment]
Last minor request: the value stored is a variance, but the key name is sigma_g, suggesting is the rms. I would either change the name to gauss_variance or sigma2_g, or store the square root of the variance and keep the current name.

**Comment by fjaviersanchez** [comment]
What is stored is the square root of the variance :)

**Comment by andreufont** [comment]
Ouch! 
Ready to go then. Thanks!

**Comment by damonge** [comment]
@fjaviersanchez , thanks a lot for doing this. To avoid having to resolve too many conflicts, given that the skewers branch is a bit outdated, I've copied your modifications into a new branch that branches off directly from master. Can you (and @andreufont ) have a look there and see if everything makes sense?

**Comment by damonge** [comment]
Let's

**Pull request closed without merging**
